#!/bin/sh

# Make sure that new files generated by Docker have group write permission
source /entrypoints/00-umask.sh

# Druid prompt with fire
if [ "$PS1" ]; then
  NORMAL="\[\e[0m\]"
  RED="\[\e[1;31m\]"
  YELLOW="\[\e[1;33m\]"
  PS1="🔥 ${YELLOW}[${APP_ENV:-Unknown}] ${RED}[${HOSTNAME}] ${YELLOW}\w${NORMAL} $ "
fi

# Aliases
alias ll="ls -lah"
alias make="make -s"

# Run neofetch on login
neofetch --ascii_colors 1 --ascii /home/druid/ascii
