[global]
; Error log level. Possible values: alert, error, warning, notice, debug. Default value: notice.
log_level = notice
process_control_timeout = 30

[www]
user = www-data
group = www-data
; listen = [::]:9000

pm = dynamic
pm.max_children = 8
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 500
pm.process_idle_timeout = 60s

; Allow environment variables to reach PHP via getenv()
clear_env = no

; Redirect worker stdout/stderr to main error log
catch_workers_output = yes

php_value[memory_limit] = 512M

pm.status_path = /status
ping.path = /ping
