version: '3.7'

services:

  nginx:
    hostname: "${DRUPAL_HOSTNAME}"
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    image: druidfi/nginx:1.18-drupal
    volumes:
      - .:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.rule=Host(`${DRUPAL_HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-nginx.loadbalancer.server.port=8080"
      - "traefik.docker.network=stonehenge-network"
    networks:
      - internal
      - stonehenge-network
    depends_on:
      - app

  app:
    container_name: "${COMPOSE_PROJECT_NAME}-php"
    image: druidfi/drupal:7.3
    volumes:
      - .:/app:delegated
    #  - ssh:/tmp/amazeeio_ssh-agent:ro
    environment:
      DRUSH_OPTIONS_URI: "https://${DRUPAL_HOSTNAME}"
    networks:
      - internal
    depends_on:
      - db

  db:
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: druidfi/db:mysql5.7-drupal
    #volumes:
    #  - db_data:/var/lib/mysql
    ports:
      - 3306
    networks:
      - internal

networks:
  internal:
    external: false
  stonehenge-network:
    external: true

#volumes:
#  db_data:
#  ssh:
#    name: stonehenge-ssh
#    external: true
