name: Database images

permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths:
      - 'db/**'
      - '.github/workflows/db.yml'
  pull_request:
    paths:
      - 'db/**'
      - '.github/workflows/db.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-26.04

    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Build database images
        run: make db-bake-test
