name: Database images

on:
  push:
    branches: [ main ]
    paths:
      - 'db/**'
  pull_request:
    paths:
      - 'db/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - db: 'mariadb'
            version: '10.5'
          - db: 'mariadb'
            version: '10.6'
          - db: 'mysql'
            version: '5.7'
          - db: 'mysql'
            version: '8.0'

    steps:

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build ${{ matrix.db }} ${{ matrix.version }} image for Drupal
        run: |
          cd db
          docker buildx bake --pull --progress plain --no-cache --load --set *.platform=linux/amd64 \
            ${{ matrix.db }}-${{ matrix.version }}
