name: Misc images

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Curl image
        run: make build-curl

      - name: Build dnsmasq image
        run: make build-dnsmasq

      - name: Build Mailhog image
        run: make build-mailhog || true

      - name: Build SAML IdP image
        run: make build-saml-idp

      - name: Build SSH agent image
        run: make build-ssh-agent

      - name: Build Varnish image
        run: make build-varnish

#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@master
#        with:
#          image-ref: 'druidfi/db:mysql${{ matrix.mysql }}-drupal'
#          format: 'table'
#          exit-code: '1'
#          ignore-unfixed: true
#          severity: 'CRITICAL,HIGH'
