name: Nginx images

on:
  push:
    branches: [ main ]
    paths:
      - 'nginx/**'
      - '.github/workflows/nginx.yml'
  pull_request:
    paths:
      - 'nginx/**'
      - '.github/workflows/nginx.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Build Nginx images
        run: make nginx-bake-test
