name: Node images

on:
  push:
    branches: [ main ]
    paths:
      - 'node/**'
      - '.github/workflows/node.yml'
  pull_request:
    paths:
      - 'node/**'
      - '.github/workflows/node.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [ 8, 10, 12, 14 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Node ${{ matrix.node }} image
        run: |
          cd node
          docker buildx bake --pull --progress plain --no-cache --load --set *.platform=linux/amd64 node-${{ matrix.node }}
